### ISSUE TITLE
split up source repository

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1830]
## CodeChecker common
* main script to handle sub commands

## Analyzer handling part: 
* log
* analyze
* parse
* local diff
* tu collector
* plist parser
* html report generator

## Client to manage remote server:
* store
* cmd
* remote diff

## Database server:
* server to handle database backends (SQlite, PostgreSQL)

## TODOs
- [x] - Add targets to build analyzer/server separately
- [ ] - Enable tu collector test cases on osx (travis).
- [x] - Rename libcodechecker to codechecker.
- [ ] - Run server  tests without CodeChecker analyze command (generate and commit plist files).
- [x] - Split up documentations

## Directory layout
```
tools
  |- tu_collector
  |- plist_to_html
config
analyzer
  |- bin
  |- cmd
  |- config
    |- analyzer_version.json
  |- codechecker_analyzer
    |- __init__.py
    |- analyze_context.py
    |- analyzers
      |- clangsa
      |- clangtidy
    |- buildlog
  |- requirements_py
    |- dev
    |- test
  |- tests
    |- unit
    |- functional
  |- tools
    |- build_logger
  |- .noserc
  |- Makefile (run tests, linters, build analyzer only package)
  |- requirements.txt (runtime)
  |- setup.py (create python wheel)
  |- tox.ini
web
  |- api
  |- codechecker_web
    |- shared
  |- config
    |- web_version.json (api version, db version, web version)
  |- client
   |- bin
   |- cmd
   |- codechecker_client
     |- __init__.py
   |- requirements_py
    |- dev
    |- test
  |- server
    |- bin
    |- cmd
    |- config
      |- db_version.json
    |- codechecker_server
      |- auth
      |- api
      |- database
      |- migrations
        |- config (config database migration scripts)
        |- report (report database migration scripts)
    |- requirements_py
      |- dev
      |- test
  |- tests
    |- analyzer_reports (plist files for the tests)
    |- unit
    |- functional
  |- vendor
    |- Makefile
  |- www

  |- requirements_py
  |- Makefile (run tests, linters, build client/server only package)
  |-...
  |- requirements.txt (runtime)
  |- setup.py (create python wheel)
  |- tox.ini

codechecker_common
  |- __init__.py
  |- plist_parser.py

docs
  |- analyzer
    |- ...
  |- server
    |- ...
  |- README.MD

package
  |- bin
  |- cmd
  |- extend_version.py
  |- create_commands.py

scripts (to run all the tests (analyzer, server), build the package ...)
```

**Comment by gyorb** [comment]
@csordasmarton I've added a proposed directory layout, I'm still thinking how to handle the different python requirements.txt files the best way, maybe we should simplify them to two:
- requirements during runtime
- requirements for development

Maybe separate analyzer_reports directories for the unit and functional tests would be better.

**Comment by gyorb** [comment]
The new layout is done for now.
