### ISSUE TITLE
Refactoring of compiler_info.json handling

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#2045]
In #1908 there is an extension which will get the compiler info for both languages which changes
- [ ] the `compiler_info.json` loading introduced in #1906 and #2039.
- [ ] The recently added `renew_info_files.py` debug script needs to be updated too: #1909
- [ ] And the other debug scripts in #1941 and #2044.

**Comment by dkrupp** [comment]
Also we need to factor out the compiler_info.json creation and the compiler auto-detection from parse_unique_log() function from log_parser.py to make it more testable.

**Comment by gyorb** [comment]
@balazske this discussion is related to the changes done in #2903 I think #2903 solves the 3rd point in the list
