### ISSUE TITLE
CodeChecker license change

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#2697]
## Why will be the license changed?

As you know the source code is right now licensed under the lesser known
University of Illinois/NCSA Open Source License (NCSA).

In the last year the LLVM project including Clang and Clang-tidy went through a re-licensing process. The license from NCSA license was changed to "Apache 2.0 with LLVM Exception".
You can read more about the change [here](http://llvm.org/foundation/relicensing/)

The CodeChecker project is closely related to these projects and after some discussion in the team we decided to change the license of the CodeChecker project to the better known "Apache 2.0 with LLVM Exception" license.

## More details about the new license can be found here
License Full Name: "Apache 2.0 with LLVM Exception"
SPDX License Identifier: "Apache-2.0 WITH LLVM-exception"

https://spdx.org/licenses/Apache-2.0.html
https://spdx.org/licenses/LLVM-exception.html

Full license text:
http://llvm.org/foundation/relicensing/LICENSE.txt

## Tasks to be done to change the license

- [x] contact contributors about the license change

License files which needs to be changed:
- [x] LICENSE.TXT
- [x] tools/codechecker_report_hash/LICENSE.txt
- [x] tools/plist_to_html/LICENSE.txt
- [x] tools/report-converter/LICENSE.txt
- [x] tools/tu_collector/LICENSE.txt
- [ ] web/api/js/codechecker-api-js/LICENSE     // new version needs to be published npm
- [ ] web/api/js/codechecker-api-node/LICENSE   // new version needs to be published npm
- [ ] web/api/py/codechecker_api/LICENSE        // new version needs to be published pypi
- [ ] web/api/py/codechecker_api_shared/LICENSE // new version needs to be published pypi
- [x] analyzer/tools/compilation-database-transformer/LICENSE.txt

New license header 
- [x] the license header needs to be changed in each source file
```
# -------------------------------------------------------------------------
#
#  Part of the CodeChecker project, under the Apache License v2.0 with
#  LLVM Exceptions. See LICENSE for license information.
#  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# -------------------------------------------------------------------------
```

## Planed license change date

**The plan is to change the license after the v6.12 release which is expected to be released around the 12th of May 2020.**

Every contribution after the release tag will be done under the new license.
