### ISSUE TITLE
refactoring and cleanup

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#345]
- [x] cleanup and refactor database schema #343
- [x] thrift client api modification #344
- [x] cleanup GUI source #343
