### ISSUE TITLE
Cleanup command line arguments

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#415]
Cleaning up command line arguments might break backward incompatibility.
With the command line cleanup remove the deprecated command line arguments too.
- [x] add a configuration option listen address #331
- [x] `-v` flag should be used for verbose mode for all the sub commands #225
- [x] cleanup skip list and steps (quickcheck) args #575

**Comment by AlexTelon** [comment]
Any particular ones planned right now? I hope that a detail list of which arguments were changed/removed is made once this is done?

Im all in favor of a cleanup! Just want to know if anything is going to change that breaks explanations Im doing in my thesis :)

**Comment by gyorb** [comment]
We plan to remove all the arguments which are deprecated.
Another backward incompatible change will be that the -v  flag will be used to set verbosity for every sub commands. Right now it is used for view-port under the server sub command.
The v6.0 release will break database schema and the command line and maybe our thrift API too. That is why we plan a new major release.
Many things will be simplified and improved  but some changes we can not do without breaking backward incompatibility.

**Comment by Xazax-hun** [comment]
I think we should also reserve the command line arguments for fixits to avoid any possible conflicts with the current flags. See #326.

**Comment by Xazax-hun** [comment]
Probably a command line option for #380 should be reserved as well.

**Comment by bruntib** [comment]
Verbose flag is done, but it's `--verbose` instead of `-v`. This latter one is used as view server port.

**Comment by whisperity** [comment]
Let's spice up the discussion about this as the new commands and command interfaces are just around the corner. `log` has already been ported to a proposed new layout (see #610), but the invocation of `log` is the easiest.

**Comment by whisperity** [comment]
In #639:
The argument list of `quickcheck` was not changed (so `-s` is still `--print-steps`), but `-s` has been removed from the option token for skipfiles in `analyze`. Just as how, `-u` is no longer an argument for suppress in `parse` and `store`.
