### ISSUE TITLE
Tracking issue for VS Code use cases

### ISSUE THREAD

**Issue by Discookie** [Ericsson/codechecker#4251]
Tracking issue for various VS Code-related use cases, that are needed for making the UX for the "Reports in current file" on the IDE side better. See Ericsson/CodeCheckerVSCodePlugin#149.

- [ ] There should be a way to query the list of files that will be analyzed by a `CodeChecker analyze` command, even if it's only displayed at the start of its execution.
- [ ] CodeChecker should store the reason why the analysis of a specific file failed. (And then be able to query it per-file with `CodeChecker parse`.)
- [ ] CodeChecker should store historical failed analyses, either incrementally or on a per-file basis, and not just the last run's succeeded/failed files.
- [ ] CodeChecker should be able to return whether a file has been analyzed or not. The three distinct cases here are not in the compilation database, in the compilation database but not analyzed, in the compilation database and analyzed.
- [ ] If CodeChecker is killed or a timeout is reached, the fact that a timeout occured should be saved as if it was an error, similar to storing failure reasons.
