### ISSUE TITLE
Finish subcommand revamping

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#638]
# Subcommands in the new layout

(`✓` means that the thing has been merged.)

 - [X] `log` #610
 - [x] `analyze` #639
 - [x] `parse` #639
 - [x] `store` #639
 - [x] `check` (wrapper) #639
 - [x] `quickcheck` (wrapper) #639
 - [x] `plist` (wrapper) #639
 - [X] `analyzers` #629
 - [X] `checkers` #634
 - [x] `server` #655
 - [x] `cmd` #666
 - [x] `debug` #656
 - [x] `version` #657

Also:

- [x] Subcommands should go into a subfolder of `libcodechecker`, not directly into the main dir. #707
- [x] Better output for available subcommands in installer. #706

# Various other TO-DO
 - [x] _Clang Static Analyzer_ and _Clang-Tidy_ should be [links](http://example.org) in the `README.md`. #706
 - [x] Clean-up and fix `docs/user_guide.md`. #706

**Comment by whisperity** [comment]
@gyorb Will do this tomorrow too.

**Comment by gyorb** [comment]
@whisperity no problem we will finish it in 5.9
