### ISSUE TITLE
Multiple products on the same server (multi-database system) [142h]

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#691]
# Synopsis

In `5.8`, a server stores multiple runs, but these runs are stored in the same database and to access the results, the same authentication configuration is used. This makes separation of "products" harder, as different databases as authentication files must be set up, **and** multiple CodeChecker servers must run on different TCP ports.

This new feature will enable the configuration of multiple "products" under the same single server.

# Model

## Each *server* will have

 * A **superuser credential** (username and password) that is
   * Either:
     * Random generated and showed at first server start
     * Input in the terminal that first starts the server
   * Stored securely in a configuration file, in `--config-directory`.
 * A `--reset-root-account` command-line option (or something like that) that will make the server act like it's its first start.
 * A **single** authentication **`session_config.json`** that dictates which authentication modes are enabled and configures credential store(s). (This is the same functionality that has been originally implemented in #393.)
 * The **root** name and password is **NOT** authenticated against the privilege backend. It always has access, and has every access.
 * A "master" database connection that stores dynamic configuration.
   * The *"database arguments"* of `CodeChecker server` change to specifying this new "master" database.
   * **Dynamic configuration** means:
     * A list of users and groups (these are now users and their authenticative PAM/LDAP groups they belong to) that are **also** given *superuser* privileges.
     * The list of _products_. **Products** take over the concept of what currently is handled by a unique server instance.
        * The _master_ database stores product-related **configuration**, but not product-related data. (See below.)
    * All superusers can change this configuration.

## Each *product* will have

 * A product configuration, stored in the **master** database:
   * Editable only by **superusers**:
      * A unique product _endpoint_ in the server's URL.
        * **Restrictions:** There are some reserved endpoints, thus the product's URL can **NOT** be `Admin`, `Products`, `Authentication`, `CodeCheckerService`, `fonts`, `scripts`, etc. Can **NOT** contain `/`, `_`, `?`, and maybe not even other special characters. Can NOT begin with _number_.
        * Initially. this is generated from the product's name.
        * Later, we might allow the *superusers* to set arbitrary custom URLs.
      * Its own database connection. (See below.)
   * Editable by **product admins**:
     * A unique product display name.
     * A description.
     * A list of users and PAM/LDAP groups, which are given *product admin* rights.
     * A list of users and PAM/LDAP groups who can *access* the product, i.e. check in and view analysis results. (This *COULD* later on be expanded for more fine-grained access control later.)
     * Being *product admin* automatically means having *access*.
 * A **product-specific database**, that stores analysis results. This is the database schema that is currently #723 used by every CodeChecker server instance.

## Notes

In case authentication is disabled on the server, as no credentials are asked:
 * Everyone has check-in and view-results access to every product
 * Only the **root** user can log in with the hard-configured credentials, and edit every setting.
 * The concept of *product admin* is irrelevant, **no one** can edit product-specific settings (except for **root**)

# View

`CodeChecker server` runs on a single URL, e.g. [`http://codechecker.ericsson.se:9000`](http://codechecker.ericsson.se:9000).

Title bar changes so it shows the user's name somewhere.

![Mock of new views](https://user-images.githubusercontent.com/1969470/28171841-06837ec6-67ea-11e7-9af5-a2685c29da9b.png)

> Below, _Valid-User_ means a successful authentication OR a server that does not require authentication.

## Login screen

**At:** `/`
**If:** the user has not logged in AND the server requires authentication

Classical, trivial login window. Least priority, the normal HTTP `Authorize` header (Browser pop-up window) shall suffice initially.

## Product list

**At:** `/`
**If:** Valid-User

Has a button for the server administration panel (**to** `/Admin` **if** Superuser). Lists products. Clicking on a product brings the user **to** `/[product-url]`.

Shows error message and strikes out the product if it's not accessible to the user OR the database connection failed.

### Questions

 * Show **every** product and `disable` or ~~strike-through~~ those the user can't access?
 * Only show products the user can access?
 * Or maybe this should be toggle-able by superusers?

## Run list

**At:** `/[product-url]`
**If:** Valid-User AND user can access this product

Run list same as CodeChecker homepage in `v5.8`. Extra things are a _Back to Products_ button (**to** `/Products`) and a product administration button (**if** Valid-User AND Product-Admin for this product, **to** `/[product-url]/Admin`). Other functionality remains the same as before.

## Product admin page

**At:** `/[product-url]/Admin`
**If:** Valid-User AND Product-Admin for this product

Has configuration options for the product.

## Superuser site

**At:** `/Admin`
**If:** Superuser

Shows the server-wide configuration options.

# Command-line

## `server`

 * Extends with `--reset-root-account`.
 * `--sqlite` is removed, completely. The configuration database is stored under `$CONFIG_DIR/server_config.sqlite`.
   * At server start, the user is asked if they want to create a default product (with endpoint `/Default` (empty string)), and if so, where its **sqlite** database should be. (Default is `$CONFIG_DIR/product.sqlite`.)
   * A "default product" with PostgreSQL connection can **NOT** be created this way.
 * `--postgresql` joins the arguments `--db*`.
   * **In `--postgresql` mode:** The server connects to and configures an _empty_ master configuration database. It is the root's responsibility to add product connections (either SQLite or PostgreSQL) later on.

## `store` (and thus, `check`), `cmd`

 * `--host` and `--port` replaced by `--server PRODUCT_URI` that is the full qualified URI of the target product's namespace (e.g. `codechecker.ericsson.se:9000/MyProduct`)

# TO-DO list

 - [x] Discussing this issue [∞h]
 - [X] Database model and handling for master server [8h]

## First implementation patch (#773)

 - [x] Handling "run-once", the **very first** start of the server [6h]
 - Product list when opening `/`
   - [x] List products nicely [8h]
   - [x] Show database failure and lock product if such [4h]
   - [x] Placeholder for locked products [1h]
 - Handling of different products
   - [x] Creation of new products: storing the product data in the master database [1h]
   - [x] Handling database connection to newly added database [4h]
   - [x] Handling misconfigured database **at server startup** [2h]
   - Segmentation of endpoints from connecting clients (CLI code):
     - [x] `cmd` [2h]
     - [x] `store`, `check` [1h]
   - [x] Run list view presented on endpoint (website) - includes `GET` and `POST` routing [6h]
   - [x] Update test infrastructure and existing tests [10h]
 - [x] Product management in the command-line, for basic `add` and `remove` [6h]
 - [x] Extend documentation [1h]

## Second implementation patch (#857)

 - [X] Root user handling [12h]
 - Handling of different products
   - Creation of new products
     - [x] Sanitise user input, such as restrictions on the product endpoint
 - [x] Extend tests [4h]
 - [x] Update documentation [3h]
 - [x] Permission API and internal layout [24h]
 - [x] Permission manager interface (make it reusable) [12h]
 - Superuser view:
   - [x] Restricting view for superusers [1h]
   - [x] Adding new products [12h]
   - [x] Editing product settings [4h]
   - [x] Product removal [3h]
 - Product admin view
   - [x] Restricting view for product admins [0.5h]
   - [x] Show relevant administration buttons even if user is NOT superuser. [2h]
 - [x] Locking already existing API calls based on permissions [1h]

## Further TO-DO (fluff)

 - Product list when opening `/`
   - [ ] Query extra information such as last run's data [4h]
